# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-01 10:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_auto_20171201_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingFollows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='private_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pendingfollows',
            name='follow_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_follow_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pendingfollows',
            name='target_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_account', to=settings.AUTH_USER_MODEL),
        ),
    ]
