# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-01 10:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_auto_20171201_1040'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pendingfollows',
            unique_together=set([('target_user', 'follow_user')]),
        ),
    ]
